controllers:
    resource: ../src/Controller/
    type: attribute

app_stackoverflow_data:
    path: /api/stackoverflow_posts
    controller: App\Controller\StackOverflowController::getStackOverflowData
    methods: GET

app_stackoverflow_data_questions:
    path: /api/stackoverflow_questions
    controller: App\Controller\StackOverflowController::getStackOverflowDataQuestion
    methods: GET

app_stackoverflow_data_answers:
    path: /api/stackoverflow_answers
    controller: App\Controller\StackOverflowController::getStackOverflowDataAnswers
    methods: GET